### ISSUE TITLE
Browser window being moved when infowindow.setTimeout is called

### ISSUE THREAD

**Issue by drichard1989** [googlemaps/google-maps-services-js#612] opened 2021-06-09 19:42 UTC
Hello, 

We use Google Maps in an Angular application using the google maps javascript library to display live data for our assets in an infowindow that we update every 5 seconds on an interval. It appears that when the map has an infowindow.setContent function call on it, and the infowindow is open, if the infowindow is not in view of the browser, it will scroll the window to where the infowindow is visible. See attached GIF and below code. 

	this["intervalId" + index] = setInterval(() => {
                    if (this.isWidgetInView) {
                        let test = `<div class='firstHeading' style='font-size: 12px'><b><span style='color:teal;'> ${contentString} </div></b>${this.recreateTagString(gse)}</div>`;
                        infoWindow.setContent(test);

                        let evaluationObject: any = this.gseService.determineAssetImageFromAssetType(gse);
                        if (evaluationObject !== {}) {
                            marker.setIcon(evaluationObject.stringPath);
                            if (evaluationObject.alarmType === "Critical") {
                                marker.setAnimation(google.maps.Animation.BOUNCE);
                            }
                        }
                    }
				}, 5000);

I can confirm that it does not occur when commenting out infoWindow.setContnet(test), and can confirm it does not occur if the infowindow is closed. 
![scrollbar jumping](https://user-images.githubusercontent.com/20600564/121418593-ba87b080-c930-11eb-9842-b16a54a5ba12.gif)

**Comment by jpoehnelt** [comment] 2021-06-09 19:49
Can you add these details to https://issuetracker.google.com/190075886? I'm going to close this issue since it is unrelated to this repository. I have set the priority higher on this bug internally, see the linked issue for more information and status updates.

**Closed** 2021-06-09 19:49 UTC
Labels: triage me, type: bug

**Comment by jpoehnelt** [comment] 2021-06-09 19:52
As a work around, you might be able to use `infowindow.setOptions({shouldFocus: false})`. I have not confirmed this.

**Comment by drichard1989** [comment] 2021-06-09 20:38
I tried that, and it did not seem to help. Added details to the link provided. Thank you so far!

**Comment by jpoehnelt** [comment] 2021-06-09 20:42
I believe a fix will be released later this week for `setContent` if you are using `v=weekly`, in the meantime you can pin to `v=3.44` which I believe does not have this problem.

**Comment by romainwurtz** [comment] 2021-06-16 02:54
Pinning to `v=3.43.8a` fixed the issue on our end.
