### ISSUE TITLE
Keep alive issue

### ISSUE THREAD

**Issue by rotero** [googlemaps/google-maps-services-js#43] opened 2016-10-07 17:28 UTC
If been using the directions and the geocoding calls to the Maps API and both of them seem to have an issue. after firing a request and handling the response node doesn't exit the script due to the keep alive's in the response. isn't there a way to manipulate the request in a way, that the connection is not kept alive, or a call to actively close the connection (process.exit is not an option)

**Comment by stephenmcd** [comment] 2016-10-08 06:05
I believe this was resolved in 59e1fca99993d1e3f6dc4986f72fc88d1781d0c3 - can you confirm?

**Comment by tonybadguy** [comment] 2016-10-09 07:00
I was running into the same issue for geocoding calls and can confirm that the problem is resolved on the current master branch. However, the latest npm package 0.2.1 is not up to date with master. Will you be pushing out an updated package?

**Comment by rotero** [comment] 2016-10-09 14:15
i can confirm that the latest npm version still has the bug. 
will try to switch to master and reconfirm

**Closed** 2016-10-17 01:58 UTC
