### ISSUE TITLE
Geometry Library

### ISSUE THREAD

**Issue by nasr18** [googlemaps/google-maps-services-js#187] opened 2018-07-30 18:35 UTC
It would be very useful if you provide these options....

https://developers.google.com/maps/documentation/javascript/geometry#poly

**Comment by amuramoto** [comment] 2019-06-28 00:45
Closing as duplicate of https://github.com/googlemaps/google-maps-services-js/issues/216

**Closed by amuramoto** 2019-06-28 00:45 UTC
