### ISSUE TITLE
Photo place is badly displayed

### ISSUE THREAD

**Issue by Code202** [googlemaps/google-maps-services-js#396] opened 2020-04-19 09:36 UTC
Hi, I encounters a problem with using the `placePhoto()` call, I receive a quare instead of the place photo.
Here is my function to get a place photo by its reference:
```
async function getPhotoByReference(photoReference: PlacePhoto): Promise<PlacePhotoResponse> {
  const placePhototRequest: PlacePhotoRequest = {
    params: {
      photoreference: photoReference.photo_reference,
      maxheight: photoReference.height,
      maxwidth: photoReference.width,
      key: GOOGLE_MAPS_API_KEY
    }
  };

  return GoogleMapsClient.placePhoto(placePhototRequest);
}

```
And here is the routing:
```
router.get('/photo/:ref', async (req: Request, res: Response) => {
  const ref = _.get(req.params, 'ref');
  const placePhoto = {
    photo_reference: ref,
    height: 100,
    width: 100
  } as PlacePhoto;

  try {
    const resp = await restaurantManagerService.getPhotoByReference(placePhoto);
    console.log(resp.status);
    res.set(resp.headers).send(resp.data);
  } catch (error) {
    res.send(error);
  }
});

```
I have already verified the photo reference with a cull request and it'working fine but unfortunately it does not with google-maps-services-js. I don't know what I a am doing wrong.

**Comment by jpoehnelt** [comment] 2020-04-20 16:52
What is the error?

**Comment by Code202** [comment] 2020-04-20 17:02
I am getting this response on postman
![Capture d’écran de 2020-04-20 18-57-24](https://user-images.githubusercontent.com/47416535/79778666-6a6b1a80-8339-11ea-9e2f-21ba8e9f7e00.png)

**Comment by jpoehnelt** [comment] 2020-04-20 17:22
What are the response headers in postman?

**Comment by Code202** [comment] 2020-04-20 17:25
Here are the headers response:

![Capture d’écran de 2020-04-20 19-23-54](https://user-images.githubusercontent.com/47416535/79780766-b4a1cb00-833c-11ea-9f20-199b00e6c6fd.png)

**Comment by jpoehnelt** [comment] 2020-04-20 17:30
Looks like the content type is there. At this point, it would be useful to separate the proxy/postman from the underlying call to the API. I also found this: https://stackoverflow.com/questions/35524070/images-not-displaying-in-postman

**Comment by Code202** [comment] 2020-04-20 17:49
Actually on my config on postman, the proxy and the interceptors are off. I'm stuck and have no clue

**Comment by jpoehnelt** [comment] 2020-04-20 17:55
Let's start by removing postman. Can you take the request and use curl to make the request against your proxy and write the response to a file?

**Comment by jpoehnelt** [comment] 2020-04-20 17:56
Next try and remove the proxy. Use curl to make a request to the photo endpoint and write that to a file. Is it the same as above?

**Comment by Code202** [comment] 2020-04-20 18:18
the first request curl did respond the same corrupted file, but the second request to the photo endpoint worked like a charm

**Comment by jpoehnelt** [comment] 2020-04-20 18:31
So it seems like something in the proxy is causing the issue.

**Comment by jpoehnelt** [comment] 2020-04-20 18:50
I think the issue might be the content-encoding. The original response headers from Google API are returning a gzipped body which axios decodes for you. You are returning this header but with the decoded body.

**Comment by jpoehnelt** [comment] 2020-04-20 18:52
I am going to close this for now as I do not believe it is related to this library or the API. Please reopen if you find otherwise. It would be great if you could comment here with the solution.

**Closed by jpoehnelt** 2020-04-20 18:52 UTC
Labels: needs more info

**Comment by Code202** [comment] 2020-04-20 18:54
ok I'll keep investigating on the issue, if I find the fix I'll share it here. Thanks for your answers

**Comment by mendrik** [comment] 2020-06-07 18:19
I wanted to add I also experience the same, the problem is the res.data stuff looks like jpeg but seems corrupt. Is there some buffer not read until the end or something?

` const imgRes = await client.placePhoto({
                params: {
                    key: PHOTOS_KEY,
                    photoreference: photos[0].photo_reference,
                    maxwidth: 480
                },
            });
            res
                .status(200)
                .set(imgRes.headers)
                .send(imgRes.data)
                .end()`

That's my code on the a cloud nodejs function.
